.travis.yml
README.md
src/__tests__/index-test.js

TravisCI script

---

package.json
src/__tests__/index-test.js
src/index.js
src/pathNotEq.js
src/propNotEq.js

Added new function - propNotEq.

function - propNotEq

---

src/cx.js

Fixed JS doc example for cx function.

fixed cx function jsdoc example

---

src/__tests__/index-test.js
src/index.js
src/joinWithDash.js
src/joinWithUnderscore.js
src/toKebabCase.js
src/toScreamingSnakeCase.js
src/toSnakeCase.js

Introduced new functions joinWithDash and joinWithUnderscore.

functions - joinWithDash and joinWithUnderscore

---

package.json

Contains script launching tests with coverage.

added script shortcut to run tests with coverage

---

packages/ramda-extension/src/trace.js

Make trace point-free

---

packages/ramda-extension/src/__tests__/composeC-test.js
packages/ramda-extension/src/__tests__/pipeC-test.js
packages/ramda-extension/src/composeC.js
packages/ramda-extension/src/index.js
packages/ramda-extension/src/pipeC.js

UPDATE: added pipeC and composeC functions

---

packages/ramda-extension/src/__tests__/padLeft-test.js
packages/ramda-extension/src/__tests__/padLeftUntil-test.js
packages/ramda-extension/src/__tests__/padRight-test.js
packages/ramda-extension/src/__tests__/padRightUntil-test.js
packages/ramda-extension/src/index.js
packages/ramda-extension/src/padLeft.js
packages/ramda-extension/src/padLeftUntil.js
packages/ramda-extension/src/padRight.js
packages/ramda-extension/src/padRightUntil.js

new functions

---

packages/ramda-extension/package.json
packages/ramda-extension/src/__tests__/reduceSource-test.js
packages/ramda-extension/src/index.js
packages/ramda-extension/src/reduceSource.js

reduceSource allows reducing while referencing the source accumulator and array

Reduce source

---

packages/ramda-extension/src/__tests__/cx-test.js
packages/ramda-extension/src/cx.js

cx - trim class names before join

---

packages/ramda-extension/src/dispatch.js
packages/ramda-extension/src/dispatchWith.js
packages/ramda-extension/src/padLeft.js
packages/ramda-extension/src/padLeftUntil.js
packages/ramda-extension/src/padRight.js
packages/ramda-extension/src/padRightUntil.js
packages/ramda-extension/src/xPairs.js
packages/ramda-extension/src/xPairsRight.js

fixing jsdocs for dispatchWith and @see annotation all over

---

packages/ramda-extension/src/__tests__/mergeDeepAllWith-test.js
packages/ramda-extension/src/__tests__/mergeDeepAllWithKey-test.js
packages/ramda-extension/src/index.js
packages/ramda-extension/src/mergeDeepAllWith.js
packages/ramda-extension/src/mergeDeepAllWithKey.js
packages/ramda-extension/src/mergeDeepLeftAll.js
packages/ramda-extension/src/mergeDeepRightAll.js

mergeDeepAllWith, mergeDeepAllWithKey

---

packages/ramda-extension/src/toScreamingSnakeCase.js

I saw a typo when I was looking at the docs.

SCREAMINT -> SCREAMING

---

packages/ramda-extension/package.json
packages/ramda-extension/src/__tests__/cx-test.js
packages/ramda-extension/src/cx.js
yarn.lock

Many people ask about the performance of our `cx` against the original `classnames`. 
So I've created a test which reveals the cruel truth. We should try to work on the `cx` perfromance.
Current state is `Failed: cx is about 40 times slower`

CX benchmark

---

.gitignore
packages/ramda-extension/src/__tests__/camelizeKeys-test.js
packages/ramda-extension/src/camelizeKeys.js

Closes #98 
Let me know if there's anything missing or can be improved :+1:

Refactor camelizeKeys to use mapKeysAndValues

---

packages/ramda-extension/src/__tests__/isPlainObject-test.js
packages/ramda-extension/src/index.js
packages/ramda-extension/src/isPlainObject.js

Add isPlainObject

---

packages/ramda-extension/src/__tests__/flattenValues-test.js
packages/ramda-extension/src/__tests__/searchInArray-test.js
packages/ramda-extension/src/__tests__/searchInArrayWith-test.js
packages/ramda-extension/src/flattenValues.js
packages/ramda-extension/src/searchInArray.js
packages/ramda-extension/src/searchInArrayWith.js
yarn.lock

Array search

---

packages/ramda-extension/src/__tests__/applyIfFunction-test.js
packages/ramda-extension/src/__tests__/callIfFunction-test.js
packages/ramda-extension/src/applyIfFunction.js
packages/ramda-extension/src/callIfFunction.js
packages/ramda-extension/src/index.js

callIfFunction, applyIfFunction

---

packages/ramda-extension-docs/docs/index.html
packages/ramda-extension-docs/public/docs/index.html
packages/ramda-extension/src/mergeWithDotPath.js

fix of mergeWithDotPath docs

---

packages/ramda-extension/src/__tests__/isBoolean-test.js
packages/ramda-extension/src/index.js
packages/ramda-extension/src/isBoolean.js

added function isBoolean

---

packages/ramda-extension/src/__tests__/unfoldObjectDots-test.js
packages/ramda-extension/src/unfoldObjectDots.js

use mergeAllDeep instead of mergeAll

---

packages/ramda-extension/src/__tests__/groupByPath-test.js
packages/ramda-extension/src/__tests__/groupByProp-test.js
packages/ramda-extension/src/__tests__/uniqAppend-test.js
packages/ramda-extension/src/__tests__/uniqPrepend-test.js
packages/ramda-extension/src/groupByPath.js
packages/ramda-extension/src/groupByProp.js
packages/ramda-extension/src/index.js
packages/ramda-extension/src/uniqAppend.js
packages/ramda-extension/src/uniqPrepend.js

Uniq fns addendum

---

package.json
packages/ramda-extension-docs/package.json
packages/ramda-extension/package.json
packages/ramda-extension/rollup.config.js
packages/ramda-extension/src/__tests__/toUpperFirst-test.js
packages/ramda-extension/src/toUpperFirst.js
yarn.lock

fix(ramda-extension): toUpperFirst failing with empty string

---

.editorconfig
package.json
packages/ramda-extension-docs/publish.js
packages/ramda-extension/package.json
packages/ramda-extension/src/__tests__/dotPathEq-test.js
packages/ramda-extension/src/__tests__/dotPathNotEq-test.js
packages/ramda-extension/src/__tests__/mergeWithDotPath-test.js
packages/ramda-extension/src/__tests__/pathNotEq-test.js
packages/ramda-extension/src/__tests__/propNotEq-test.js
packages/ramda-extension/src/__tests__/viewWith-test.js
packages/ramda-extension/src/dotPathEq.js
packages/ramda-extension/src/dotPathNotEq.js
packages/ramda-extension/src/ensureArray.js
packages/ramda-extension/src/flattenValues.js
packages/ramda-extension/src/mergeWithDotPath.js
packages/ramda-extension/src/pathNotEq.js
packages/ramda-extension/src/propNotEq.js
packages/ramda-extension/src/xPairs.js
packages/ramda-extension/src/xPairsRight.js
yarn.lock

feat: #210 update to ramda 0.29.0
